CHANNEL_state_join = "state/join"
CHANNEL_state_leave = "state/leave"
CHANNEL_state_name_assign = "state/nameAssign"
CHANNEL_led_status = "led/status"
CHANNEL_led_command = "led/command"
CHANNEL_button_status = "button/status"
CHANNEL_pres_status = "photoresistor/status"
